### ISSUE TITLE
YARDホスティングサイトの自動更新

### ISSUE THREAD

**Issue by skymountain** [SoftwareFoundationGroupAtKyotoU/automata#103]
Git への push があると yard ホスティングサイトの方も自動的に更新してほしい．CI と同時に
http://www.rubydoc.info/find/github?q=automata
へ POST リクエストを送ればよさそう?

**Comment by krtx** [comment]
http://rubydoc.tenderapp.com/kb/git-integration/adding-a-rubydocinfo-post-receive-commit-hook-on-github

**Comment by krtx** [comment]
追加してみたけど、なんか失敗してる

**Comment by krtx** [comment]
http://rubydoc.info/checkout ではなくて http://www.rubydoc.info/checkout だった

**Comment by krtx** [comment]
いえ〜い✌
