### ISSUE TITLE
ファイル毎に提出

### ISSUE THREAD

**Issue by krtx** [SoftwareFoundationGroupAtKyotoU/automata#106]
提出は zip ファイルをまとめてから行うようにしていますが、オプションとして、提出すべきファイルを指定し（例えばレポート、問題１、問題２、など）、それぞれの指定毎にファイルを提出できるようにもしたいです。

- zip でまとめる必要があること
- 含めるべきファイルを含めずに提出してしまうこと
- 不要なファイルを含めてしまうこと

が改善されると思います。

**Comment by OKU1987** [comment]
その機能はあったほうが良いですね

**Comment by krtx** [comment]
#134 で zip ファイルの中を見て必要なファイルがなければ要再提出になるようになりました。multiple files は TODO です。
