### ISSUE TITLE
絞り込み表示

### ISSUE THREAD

**Issue by krtx** [SoftwareFoundationGroupAtKyotoU/automata#119]
複数人で TA をするとき

- 学生毎で分担する
- 課題毎で分担する

のいずれかの仕方がありますが、前者の場合に担当する学生だけを限定して表示する仕組みがあると

+ 読み込みが早くなる（サーバ側でユーザを絞る場合）
+ 見やすい 

ようになると思いますが、どうでしょうか。

**Comment by OKU1987** [comment]
良いと思います

**Comment by h-inoue** [comment]
採点基準を揃えるため等、僕は他のTAの添削状況を見る場合もありましたが、皆さんはどないでしょう。
オプションとして用意しておくのはよいと思います。

**Comment by OKU1987** [comment]
自分は課題事の分担のみでしたが，確かに，採点基準を揃えたいときに自分の担当学生しか見れないのは不便ですね…

**Comment by krtx** [comment]
デフォルトで担当学生だけ、オプションで全ての学生を読み込むのでどうでしょうか

**Comment by OKU1987** [comment]
それで良いと思います
