### ISSUE TITLE
Java Applet

### ISSUE THREAD

**Issue by h-inoue** [SoftwareFoundationGroupAtKyotoU/automata#125]
現在、考えうるIssueを雑多に書いていく段階。

* jarファイル
コンパイルはユーザー側で行われ、レポートやソース等と共にjarファイルが渡されてくる。
1つ60KB程度

* Appletの表示 
表示の仕方としては、ファイル一覧よりjarファイルをクリックすると新規ウィンドウでAppletが表示される、とか
こんな感じのhtmlが生成されればよいはず。(教科書より)
```html
<html>
<head>
<title>
TouchyWindow
</title>
</head>
<body>
<h1>TouchyWindow</h1>
<table border="3">
<tr><td><applet
  code="TouchyWindow.class"
  archive="TouchyWindow.jar"
  width="150"
  height="100"
>
Note: This demo requires a Java enabled browser.  If you see this message then your browser either doesn't support Java or has had Java disabled.
</applet></td>
</table>
<p>Click below to download the source files for TouchyWindow.</p>
</body>
</html>
```

* セキュリティ 
automata本体とは無関係。
未署名アプレットを動かすために、使用者各自が例外サイトに本URLを追加する必要がある。

**Comment by h-inoue** [comment]
提出してもらうコードと表示方法について

- .classを提出してもらうのが良さそう。BlueJ(IDE)から容易に取ってこれる。

- 提出されるコードは objectdrawV1.1.2.jar というライブラリに依存するの
  で、.classのみアップロードする場合、サーバー側に置いてあるライブラリ
  を参照すれば動く。

```html
<tr><td><applet
  code="CrossedLines.class"
  archive="objectdrawV1.1.2.jar"
  width="150"
  height="100"
>
```

- .classファイルが複数ある場合、同じディレクトリに入っていれば問題なく
  動作する。(package指定している場合は分からないが、package使われなさそ
  うなので問題ないかと)

- 他にも依存ライブラリが増えるかは未定。

- Appletとして実行可能なクラスは、extends WindowControler している。
  なので、そこを見れば実行可能か判別できる。(このクラスを直接継承しない
  輩が出る可能性はあるが)

- 将来的には.classだけでなく.jarでのアップロードにも対応した方が良い。
  .jarにまとめておかないと、必要にならなければ.classを読みに行かないの
  で、レスポンスに影響する可能性がある。

**Comment by h-inoue** [comment]
教科書のサポートページを載せておきます。
http://eventfuljava.cs.williams.edu/index.html
AppletのサンプルコードやobjectdrawV1.1.2.jar は、ここより取ってこれます。

**Comment by h-inoue** [comment]
現時点での変更箇所のポイント
- ソースコードと共に.classファイルが送られてくる。ただし、依存し合
  う.classは同じディレクトリに入れてもらう。

- ファイル一覧で実行可能な.classファイルをクリックすることで、Applet用
  の新規ウィンドウが開く。

- Applet用新規ウィンドウのhtmlは自動生成されるが、それが実行時に依存す
  る情報は、基点となった.classファイル名のみ。静的には、ライブラリが置
  かれたディレクトリが必要。

**Comment by chiro** [comment]
:+1:
