### ISSUE TITLE
履歴閲覧機能

### ISSUE THREAD

**Issue by h-inoue** [SoftwareFoundationGroupAtKyotoU/automata#144]
複数の提出があった際、古い提出ファイルを閲覧する機能。
2通りの案がある。たぶん1つ目の方が簡単。

- kadai/report_id/user_id/ がルートになるように表示させる。
ルートディレクトリの場合、見られてはいけないファイルを表示させないように（タイムスタンプディレクトリのみ表示）
後続のsrcディレクトリはすっとばす。
browse.cgi の変更を頑張ればいける？

- タイムスタンプディレクトリの一覧をコンボボックスに表示させて選択できるように。
js, browse,cgiの変更、タイムスタンプディレクトリを取得するAPIの実装などが要りそう

**Comment by sowa-snow** [comment]
とりあえずcgiを頑張って前者をやるのが良いらしいということになったのでお願いします。

**Comment by h-inoue** [comment]
fixed by #397
