### ISSUE TITLE
rake のダミーユーザ登録で重複登録のチェックが動いてない

### ISSUE THREAD

**Issue by sowa-snow** [SoftwareFoundationGroupAtKyotoU/automata#176]
複数回 rake -t dummy したり、ダミーユーザとかぶってるユーザがすでに登録されてるとまずいです

**Comment by krtx** [comment]
まずいというのは具体的に

**Comment by sowa-snow** [comment]
とりあえずdata.ymlにおんなじユーザが複数入る
app.usersのほうで重複ユーザの除去とかしてないので、user.cgiとかで同じユーザが複数帰ってくる
具体的じゃないですが、色んな所でtokenがユニークなことを仮定してるのでぶっ壊れます
