### ISSUE TITLE
コメントの追加がうまくいかない ie 10

### ISSUE THREAD

**Issue by krtx** [SoftwareFoundationGroupAtKyotoU/automata#263]
http://gyazo.com/4773dafa18908f8c237be3a5acf092b6

**Comment by sowa-snow** [comment]
これたぶん`ajax.get`でキャッシュが効いてるせいなんですが、どうしましょう。

**Comment by sowa-snow** [comment]
いろいろなところでキャッシュのこと考えずに書いてるので、`api.js`のajax呼び出しのところで、{ cache: false }ってするのがいい気がします。
