### ISSUE TITLE
.js などのファイルを record/ で見ようとすると落ちる

### ISSUE THREAD

**Issue by krtx** [SoftwareFoundationGroupAtKyotoU/automata#274]

**Comment by sowa-snow** [comment]
どうして落ちるのか理解していないです。
なのでPRの修正が解決策になってるのかがわからないです。

**Comment by krtx** [comment]
/api/browse.cgi?user=id12a82d53a7d39791d4a45e2a9c301e28&report=report_4_22&path=.%2Fexamples%2Fbasic-commonjs%2Fpackage.js にアクセス
↓
末尾に .js があるので 54行目あたりのルールに引っかかる
↓
File.exist では path_info = /api/browse.cgi の存在が確認される
↓
/api/browse.cgi?user=id12a82d53a7d39791d4a45e2a9c301e28&report=report_4_22&path=.%2Fexamples%2Fbasic-commonjs%2Fpackage.js を send_file しようとするが、そんなファイルは存在しないので、エラー
