### ISSUE TITLE
api.getとかの呼び出しが失敗するたびにエラー表示がどんどん増えていく

### ISSUE THREAD

**Issue by sowa-snow** [SoftwareFoundationGroupAtKyotoU/automata#280]
`api.js`の実装側で常にエラーメッセージを追加するようになっているので、呼び出し側でエラーになる場合も想定している場合（たとえばFileViewで見ようとしたファイルがNotFoundになるとか）に止めようがないです。

**Comment by skymountain** [comment]
error アクションが設定してあれば規定の error アクションは実行しないようにします．
