### ISSUE TITLE
必修課題選択の disable 化

### ISSUE THREAD

**Issue by skymountain** [SoftwareFoundationGroupAtKyotoU/automata#354]
現在必修課題は選択していないと提出できないようになっているので，いっそのこと選択状態で disable にしてはどうか．

**Comment by skymountain** [comment]
「とりあえずいくつかの課題だけ出したい」場合でも現在は必修全てにチェックを付ける必要があるので，提出時に選択させる意味がほとんどありません．
いっそのこと最初のコメントに書いたようにするか，必修全てを選択していなくても提出できるようにするべきだと思いますが，他の人はどうでしょうか．

**Comment by weedssoul** [comment]
必修課題を選択してなくても提出出来ていいと思います.
