### ISSUE TITLE
Appletの認証を不要にしたい

### ISSUE THREAD

**Issue by h-inoue** [SoftwareFoundationGroupAtKyotoU/automata#357]
Appletを表示させる際にほぼ毎回(10分置きくらいに)Digest認証を求められるのですが，これをなくしたいです．
.classファイルに対してのみ認証をかけないようにrewrite ruleをうまく書き換えればできるんじゃないかと考えています．
そんなの危ないからやめとけとか，意見をいただければ．

**Comment by krtx** [comment]
SetEnvIf を使えばできるみたいです http://stackoverflow.com/questions/8978080/htaccess-exclude-one-url-from-basic-auth

**Comment by h-inoue** [comment]
SetEnvIfのREQUEST_URIだとcgiへのパラメータが消されてどうしようもないので，Require exprを使うとうまくいきそうです．
```
<RequireAny>
		Require valid-user
		Require expr %{QUERY_STRING} =~ /&path=.*\.class$/
</RequireAny>
```

**Comment by krtx** [comment]
ホストでアクセス制限するなど？

**Comment by sowa-snow** [comment]
ajaxで.classファイルのバイナリデータを取ってきて、File APIでBlob URL作ってObjectDOMとかに投げるとできるのかもしれない。

**Comment by h-inoue** [comment]
必要に応じて手元でいじってアクセス制限かけるということで，いったん閉じます．
