### ISSUE TITLE
アカウント登録で学籍番号かメールアドレスどちらか一方だけを間違えると利用者には修正不可能になる

### ISSUE THREAD

**Issue by sowa-snow** [SoftwareFoundationGroupAtKyotoU/automata#44]
正しい情報で再登録しようにもどちらか片方がかぶってしまうのですでに登録済みとみなされる。

**Comment by chiro** [comment]
adminがアカウントを消せるようにしましょう。

間違えて登録してしまった人には、adminがアカウントを消した上で、新しく作ってもらうということで。
