### ISSUE TITLE
コードを読んでいる時に誰のか分からなくなる

### ISSUE THREAD

**Issue by OKU1987** [SoftwareFoundationGroupAtKyotoU/automata#49]
提出されたコードが長いと、コードの下の方を読んでいるときに誰のを読んでいるのか分からなくなるので、常に学生の名前が画面内に表示されていると助かります。
解決策としては、ファイル一覧、コメント等の各タブを下にスクロールするときに、summaryが上部に固定されるようにするとよい気がします。

**Comment by krtx** [comment]
> そういえば縦の高さが600pxで固定になってるけど、画面の高さの何割とかにできないだろうか

とりあえず閉じます。
