### ISSUE TITLE
/.htaccess を追加 または 公開するディレクトリとそうでないディレクトリに分ける

### ISSUE THREAD

**Issue by krtx** [SoftwareFoundationGroupAtKyotoU/automata#75]
現状：
- 公開するファイルを集めたディレクトリ（例えば record）とそうでないファイルを集めたディレクトリ（例えば lib）が混在している
- 公開しないファイルを集めたディレクトリには .htaccess を置いてアクセスを制限している

ただし、ルートには .htaccess がないので、そのままだと見えてほしくないファイルが見えてしまいます。なので、

- .htaccess を追加する

必要があると思います。あるいは、

- 公開するディレクトリとそうでないディレクトリに分ける

ということをした方が、全体の構造がすっきりするかもしれません。どちらが良いでしょうか？

**Comment by chiro** [comment]
今、外から見られたくないファイルって、/直下のGemfileとかとlib以下、api/t以下なので、

- api/t をlib の下に移す
- /直下はきちんと .htaccess書くとかでどうでしょう。

つまり、公開したくないファイルは、基本的に lib の下に集めるってことですが。

**Comment by sowa-snow** [comment]
これやろうとして思い出したんですが、.htdigestファイルの指定が絶対パスかServerRootからの相対パスでしかできないので、.htaccessを前もって追加できないという話だった。

**Comment by krtx** [comment]
こういうのを Rakefile に追加するのはどうでしょう。

``` ruby
file '.htaccess' do

  dir = File.expand_path(File.dirname(__FILE__))

  content = <<EOF
AddType "text/html; charset=utf-8" .html

Options +ExecCGI
AddHandler cgi-script .cgi

<Files ~ "~$">
    order deny,allow
    deny from all
</Files>

<Files "*.yml">
    order deny,allow
    deny from all
</Files>

AuthType Digest
AuthUserFile "#{dir}/db/accounts/.htdigest"
AuthName "development"
Require valid-user
EOF

  open('.htaccess', 'a').write content

end
```
