### ISSUE TITLE
ファイル閲覧時にファイル形式によって適切な表示方法で表示する

### ISSUE THREAD

**Issue by sowa-snow** [SoftwareFoundationGroupAtKyotoU/automata#96]
ちらほら markdown 記法で提出してる人がいるので。
あとこのやりかたで java applet も統一的に扱える気がする。

**Comment by chiro** [comment]
https://github.com/SoftwareFoundationGroupAtKyotoU/automata/blob/master/lib/comment/renderer.rb

これに足していく感じでしょうか。

https://github.com/SoftwareFoundationGroupAtKyotoU/automata/blob/dc5e78f05528138b79493f743f6635f7e654b3eb/api/comment.cgi#L60

ここでファイル形式によって使う renderer を切り替える?

**Comment by chiro** [comment]
#304, #305 あたりである程度対応されたので閉じたい。

**Comment by krtx** [comment]
閉じてくれ〜
